export const passages = [
  "You're waiting for a train. A train that will take you far away. You know where you hope the train will take you, but you can't know for sure. Yet it doesn't matter. Now, tell me why?",
  "My name is Maximus Decimus Meridius, commander of the Armies of the North, General of the Felix Legions and loyal servant to the true emperor, Marcus Aurelius. Father to a murdered son. Husband to a murdered wife. And I will have my vengeance, in this life or the next.",
  "I don't tip because society says I gotta. I tip when somebody deserves a tip. When somebody really puts forth an effort, they deserve a little something extra. But this tipping automatically, that shits for the birds. As far as I'm concerned, they're just doin their job.",
  "Hey, I'm very sorry that the government taxes their tips. That's fucked up. But that ain't my fault. It would appear that waitresses are just one of the many groups the government fucks in the ass on a regular basis. You show me a paper says the government shouldn't do that, I'll sign it. Put it to a vote, I'll vote for it. But what I won't do is play ball. And this non-college bullshit you're telling me, I got two words for that: 'Learn to fuckin type.' Cause if you're expecting me to help out with the rent, you're in for a big fuckin surprise.",
  "I'll tell you why. I think you're a lonely person. I drive by this place a lot and I see you here. I see a lot of people around you. And I see all these phones and all this stuff on your desk. It means nothing. Then when I came inside and I met you, I saw in your eyes and I saw the way you carried yourself that you're not a happy person. And I think you need something. And if you want to call it a friend, you can call it a friend.",
  "Certain women do gravitate toward incarcerated men. It's a recognized condition. Something about the captivity of others enhances the experience of their own freedom. I assure you, it's erotic.",
  "I will miss you too, but you are wrong if you think that the joy of life comes principally from the joy of human relationships. God's place is all around us, it is in everything and in anything we can experience. People just need to change the way they look at things.",
  "If Tom had learned anything... it was that you can't ascribe great cosmic significance to a simple earthly event. Coincidence, that's all anything ever is, nothing more than coincidence... Tom had finally learned, there are no miracles. There's no such thing as fate, nothing is meant to be. He knew, he was sure of it now.",
];
